# Generated by Django 5.1.5 on 2025-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='document',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
