# Generated by Django 5.1.5 on 2025-02-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_document_quiz_document_name_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='document',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='document_name',
        ),
    ]
